title: RagingBool.Carcosa
url: https://github.com/RagingBool/RagingBool.Carcosa
summary: Carcosa is a lighting driving software that is built as part of the Unbirthday Camp.

organization: Raging Bool
tags: carcosa lighting dmx E1.31 midi party
copyright: Copyright 2015 Raging Bool
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/RagingBool/RagingBool.Carcosa/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.6.0
 - Epicycle.Math-cs.0.1.5.0
 - Epicycle.Graphics-cs.0.1.5.0

description: |
   Carcosa is a lighting driving software that is built as part of the Unbirthday Camp.
   
   * Details & release notes: https://github.com/RagingBool/RagingBool.Carcosa/blob/ver-$version$/README.md
   * Sources: https://github.com/RagingBool/RagingBool.Carcosa/tree/ver-$version$
   * Git repository: https://github.com/RagingBool/RagingBool.Carcosa